#!/usr/local/bin/bash

# a quick one off script for cleaning up coffeescript files
if [ $# -eq 0 ]; then
  echo "No argument passed. Please add in file name"
  exit 1
fi

# change all the )=> to ) =>
gsed -i "s/)->/) ->/g" $1
gsed -i "s/)=>/) =>/g" $1

# replace the newlines 
perl -p -i -e 's/\) ->\n/\) ->/g' $1
perl -p -i -e 's/\) =>\n/\) =>/g' $1


