#!/usr/local/bin/bash

# a quick one off script for cleaning up coffeescript files
if [ $# -eq 0 ]; then
  echo "No argument passed. Please add in file name"
  exit 1
fi

# change all the )=> to ) =>
gsed -i "s/)->/) ->/g" $1
gsed -i "s/)=>/) =>/g" $1

# remove empty lines beneath a function definition
perl -i -pe 'm{\) ->\s*$}...!s/^\s*$//g' $1
perl -i -pe 'm{\) =>\s*$}...!s/^\s*$//g' $1
