#!/usr/local/bin/bash

# a quick one off script for cleaning up coffeescript files
if [ $# -eq 0 ]; then
  echo "No argument passed. Please add in file name"
  exit 1
fi

# change all the )=> to ) =>
gsed -i "s/)->/) ->/g" $1
gsed -i "s/)=>/) =>/g" $1

# replace where any ->/=> is followed by an empty line
perl -00 -p -i -e 's/\) ->(?=[^\n]*\n\n)$/\) ->\n/m' $1
perl -00 -p -i -e 's/\) =>(?=[^\n]*\n\n)$/\) =>\n/m' $1

