#!/usr/bin/env python 
"""
A safe secure way to unlock your ssh/gpg keys for gpg-agent
Reads keys from env and asks you to enter passphrase, so you don't have to worry about leaving info on stdout
"""
import getpass
import os

# keys that we are entering
keys = ["GPG_KEYGRIP", "SSH_KEYGRIP"]

# check if master keyphrase file exists
try:
    with open(os.path.expandvars("$HOME/.passphrase"), "rU") as r:
        passphrases = r.read().splitlines()
except IOError:
    passphrases = None

for i,key in enumerate(keys):
    
    kg = os.getenv(key)
    if not kg:
        print "Please set %s in env" % key
        continue

    # generate the passphrase, whether in the passphrase file or by getpass
    try:
        passphrase = passphrases[i]
    except Exception as e: 
        print "enter %s passphrase:" % key
        passphrase = getpass.getpass()

    # now unlock on gpg-agent
    os.popen("gpg-preset-passphrase -c -P %s %s" % (passphrase, kg))

