#!/bin/sh

files=(

	"readme.md"
	"README.md"
)

# recommended as a pre-commit hook for python package projects
# need to check if a command exists
if [ ! `which pandoc` ]
then
	
	echo "Pandoc not found. Please update path or install"
	exit 1 
fi

# now we need to identify the input file
for file in ${files[@]}
do
	if [ -f $file ]
	then

		input_file=$file
		break
	fi
done

if [ ! -f $input_file ] 
then

	echo "No valid input files found"
	exit 1

fi

pandoc --from=markdown_github --to=rst --output=README.rst $input_file
