#!/usr/bin/env zsh

if [[ ! -d .git ]]; then
  echo "please run from a git directory"
  exit 1
fi

branches=$(git for-each-ref --format='%(refname:short)' refs/heads/)
remotes=$(git remote -v | grep fetch | awk '{ print $2 }')

for branch in $branches; do
  for remote in $remotes; do
    if ! git ls-remote "$remote" "$branch"; then
      echo -e "$branch not found on remote: $remote. Deleting local version"
      git branch -D $branch
      break
    fi
  done
done
